### ISSUE TITLE
 AttributeError: 'ChatPreview' object has no attribute 'id'

### ISSUE THREAD

**Issue by N30Z3N** [m4mallu/clonebot#24]
```
Sleeping for 4s (required by "channels.GetMessages")

2021-09-26T08:17:41.018533+00:00 app[worker.1]: [26-Sep-21 08:17:41 - ERROR] - pyrogram.dispatcher - 'ChatPreview' object has no attribute 'id'

2021-09-26T08:17:41.018556+00:00 app[worker.1]: Traceback (most recent call last):

2021-09-26T08:17:41.018557+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker

2021-09-26T08:17:41.018558+00:00 app[worker.1]:     await handler.callback(self.client, *args)

2021-09-26T08:17:41.018558+00:00 app[worker.1]:   File "/app/plugins/chat_config.py", line 70, in force_reply_msg

2021-09-26T08:17:41.018559+00:00 app[worker.1]:     chat_id = int(chat_status.id)

2021-09-26T08:17:41.018559+00:00 app[worker.1]: AttributeError: 'ChatPreview' object has no attribute 'id'

2021-09-26T08:18:56.624222+00:00 app[worker.1]: [26-Sep-21 08:18:56 - ERROR] - pyrogram.dispatcher - 'ChatPreview' object has no attribute 'id'

2021-09-26T08:18:56.624247+00:00 app[worker.1]: Traceback (most recent call last):

2021-09-26T08:18:56.624248+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker

2021-09-26T08:18:56.624248+00:00 app[worker.1]:     await handler.callback(self.client, *args)

2021-09-26T08:18:56.624249+00:00 app[worker.1]:   File "/app/plugins/chat_config.py", line 70, in force_reply_msg

2021-09-26T08:18:56.624249+00:00 app[worker.1]:     chat_id = int(chat_status.id)

2021-09-26T08:18:56.624249+00:00 app[worker.1]: AttributeError: 'ChatPreview' object has no attribute 'id'
```

**Comment by m4mallu** [comment]
This error will be raised when the repo get updated with new features. Some of the design layouts will be changed due to the update. So before using an updated repo, the existing bot interface need to be cleared (clear history) first.
