### ISSUE TITLE
Error shown after recent update

### ISSUE THREAD

**Issue by HithaishiDesai** [m4mallu/clonebot#64]
2022-07-25T11:55:49.332878+00:00 app[api]: Scaled to worker@1:Free by user hithaishitg03@gmail.com
2022-07-25T11:55:53.013978+00:00 heroku[worker.1]: Starting process with command `python3 main.py`
2022-07-25T11:55:53.604937+00:00 heroku[worker.1]: State changed from starting to up
2022-07-25T11:55:55.309463+00:00 app[worker.1]: Traceback (most recent call last):
2022-07-25T11:55:55.309478+00:00 app[worker.1]:   File "main.py", line 1, in <module>
2022-07-25T11:55:55.309568+00:00 app[worker.1]:     from bot import Bot
2022-07-25T11:55:55.309576+00:00 app[worker.1]:   File "/app/bot.py", line 4, in <module>
2022-07-25T11:55:55.309644+00:00 app[worker.1]:     from user import User
2022-07-25T11:55:55.309652+00:00 app[worker.1]:   File "/app/user.py", line 4, in <module>
2022-07-25T11:55:55.309712+00:00 app[worker.1]:     from pyrogram.enums import ParseMode
2022-07-25T11:55:55.309738+00:00 app[worker.1]: ModuleNotFoundError: No module named 'pyrogram.enums'
2022-07-25T11:55:55.505290+00:00 heroku[worker.1]: Process exited with status 1
2022-07-25T11:55:55.575429+00:00 heroku[worker.1]: State changed from up to crashed
2022-07-25T11:55:55.579355+00:00 heroku[worker.1]: State changed from crashed to starting
2022-07-25T11:55:58.677351+00:00 heroku[worker.1]: Starting process with command `python3 main.py`
2022-07-25T11:55:59.272310+00:00 heroku[worker.1]: State changed from starting to up
2022-07-25T11:56:01.209885+00:00 heroku[worker.1]: Process exited with status 1
2022-07-25T11:56:01.003330+00:00 app[worker.1]: Traceback (most recent call last):
2022-07-25T11:56:01.003346+00:00 app[worker.1]:   File "main.py", line 1, in <module>
2022-07-25T11:56:01.003416+00:00 app[worker.1]:     from bot import Bot
2022-07-25T11:56:01.003425+00:00 app[worker.1]:   File "/app/bot.py", line 4, in <module>
2022-07-25T11:56:01.003484+00:00 app[worker.1]:     from user import User
2022-07-25T11:56:01.003493+00:00 app[worker.1]:   File "/app/user.py", line 4, in <module>
2022-07-25T11:56:01.003552+00:00 app[worker.1]:     from pyrogram.enums import ParseMode
2022-07-25T11:56:01.003571+00:00 app[worker.1]: ModuleNotFoundError: No module named 'pyrogram.enums'
2022-07-25T11:56:01.278457+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by m4mallu** [comment]
This error is due to the old pyrogram version in your virtual environment. ! Uninstall all the old files and install from the new `requirements.txt`.

**Comment by HithaishiDesai** [comment]
Ok Sir, Let me check and Get back to you 🙏🏻
